### ISSUE TITLE
Need clarification

### ISSUE THREAD

**Issue by FartyPants** [Gryphe/MergeMonster#2]
It seems brilliant, but it needs some clarification. 
How are the weights in strategies determined?

  - phrase: "model"
    weight: 100
    contexts: ["as a language ", "as an AI language "]

what does the weight 100 represent?

and why in

  - phrase: "cannot"
    weight: 20
    contexts: ["I'm sorry, but I "]

it is 20...

How would I go with building bad and good strategies - how would I determine the weight?

**Comment by Gryphe** [comment]
Weight is a measure of importance, and serves as a way to balance the way the algorithm tries to meet its objective. Let's take the following situation;

Phrase 1
Probability in the model: 20%
Weight: 1

Phrase 2
Probability in the model: 2%
Weight: 1

If you yourself consider the reduction of phrase 2 just as important as phrase 1 you would apply a weight of 10 to phrase 2 so that its probability get inflated to match that of phrase 1. You could even put it higher then that.

When MergeMonster runs, each merge will be tested - If you had left phrase 2 at weight 1, a 1% reduction might not be sufficient to accept the merge, a matter which gets ridiculously complicated once you introduce a long list of phrases. However, with the new weight (10) the Monster now considers it a 10% reduction, and it might accept the merge. 

This does come with the added risk of slightly inflating phrase 1's probability again - If phrase 1 increases by 2% but the (now inflated) phrase 2 has a 10% reduction the algorithm will still accept the merge. It becomes a matter of personal preference at that point.

I hope this somewhat explains the underlying concept!

**Comment by Gryphe** [comment]
I've started working on an optional mechanism that'll automatically adjust the weights of each phrase<>context pair so that they're considered equally important for the algorithm, potentially saving a lot of future headaches.
